config/routes.rb
Rails.application.routes.draw do
  resources :pays
  resources :fuels
  resources :consumptions
  resources :trips

  root to: 'trips#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/consumption.rb
class Consumption < ApplicationRecord
end

app/models/fuel.rb
class Fuel < ApplicationRecord
end

app/models/pay.rb
class Pay < ApplicationRecord
end

app/models/trip.rb
class Trip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/consumptions_controller.rb
class ConsumptionsController < ApplicationController
  before_action :set_consumption, only: [:show, :edit, :update, :destroy]

  # GET /consumptions
  # GET /consumptions.json
  def index
    @consumptions = Consumption.all
    @fuel = Fuel.all
  end

  # GET /consumptions/1
  # GET /consumptions/1.json
  def show
  end

  # GET /consumptions/new
  def new
    @consumption = Consumption.new
  end

  # GET /consumptions/1/edit
  def edit
  end

  # POST /consumptions
  # POST /consumptions.json
  def create
    @consumption = Consumption.new(consumption_params)

    respond_to do |format|
      if @consumption.save
        format.html { redirect_to @consumption, notice: 'Consumption was successfully created.' }
        format.json { render :show, status: :created, location: @consumption }
      else
        format.html { render :new }
        format.json { render json: @consumption.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consumptions/1
  # PATCH/PUT /consumptions/1.json
  def update
    respond_to do |format|
      if @consumption.update(consumption_params)
        format.html { redirect_to consumptions_path, notice: 'Spotřeba byla upravena.' }
        format.json { render :show, status: :ok, location: @consumption }
      else
        format.html { render :edit }
        format.json { render json: @consumption.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consumptions/1
  # DELETE /consumptions/1.json
  def destroy
    @consumption.destroy
    respond_to do |format|
      format.html { redirect_to consumptions_url, notice: 'Consumption was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consumption
      @consumption = Consumption.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consumption_params
      params.require(:consumption).permit(:value)
    end
end

app/controllers/fuels_controller.rb
class FuelsController < ApplicationController
  before_action :set_fuel, only: [:show, :edit, :update, :destroy]

  # GET /fuels
  # GET /fuels.json
  def index
    @fuels = Fuel.all
  end

  # GET /fuels/1
  # GET /fuels/1.json
  def show
  end

  # GET /fuels/new
  def new
    @fuel = Fuel.new
  end

  # GET /fuels/1/edit
  def edit
  end

  # POST /fuels
  # POST /fuels.json
  def create
    @fuel = Fuel.new(fuel_params)

    respond_to do |format|
      if @fuel.save
        format.html { redirect_to @fuel, notice: 'Fuel was successfully created.' }
        format.json { render :show, status: :created, location: @fuel }
      else
        format.html { render :new }
        format.json { render json: @fuel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fuels/1
  # PATCH/PUT /fuels/1.json
  def update
    respond_to do |format|
      if @fuel.update(fuel_params)
        format.html { redirect_to consumptions_path, notice: 'Cena benzínu byla upravena.' }
        format.json { render :show, status: :ok, location: @fuel }
      else
        format.html { render :edit }
        format.json { render json: @fuel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fuels/1
  # DELETE /fuels/1.json
  def destroy
    @fuel.destroy
    respond_to do |format|
      format.html { redirect_to fuels_url, notice: 'Fuel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fuel
      @fuel = Fuel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fuel_params
      params.require(:fuel).permit(:price)
    end
end

app/controllers/pays_controller.rb
class PaysController < ApplicationController
  before_action :set_pay, only: [:show, :edit, :update, :destroy]

  # GET /pays
  # GET /pays.json
  def index
    @pays = Pay.all
  end

  # GET /pays/1
  # GET /pays/1.json
  def show
  end

  # GET /pays/new
  def new
    @pay = Pay.new
  end

  # GET /pays/1/edit
  def edit
  end

  # POST /pays
  # POST /pays.json
  def create
    @pay = Pay.new(pay_params)

    respond_to do |format|
      if @pay.save
        format.html { redirect_to trips_path, notice: 'Pay was successfully created.' }
        format.json { render :show, status: :created, location: @pay }
      else
        format.html { render :new }
        format.json { render json: @pay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pays/1
  # PATCH/PUT /pays/1.json
  def update
    respond_to do |format|
      if @pay.update(pay_params)
        format.html { redirect_to @pay, notice: 'Pay was successfully updated.' }
        format.json { render :show, status: :ok, location: @pay }
      else
        format.html { render :edit }
        format.json { render json: @pay.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pays/1
  # DELETE /pays/1.json
  def destroy
    @pay.destroy
    respond_to do |format|
      format.html { redirect_to pays_url, notice: 'Pay was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pay
      @pay = Pay.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pay_params
      params.require(:pay).permit(:price)
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
    @price = Trip.sum(:price)
    @distance = Trip.sum(:distance)
    @date = Date.today

    begin
      fuel_price = Fuel.first.price
      fuel_value = Consumption.first.value
      @km = (fuel_price * fuel_value) / 100
    rescue ActiveRecord::RecordNotFound => e
      fuel_price = 0
      fuel_value = 0
      @km = (fuel_price * fuel_value) / 100
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to trips_path, notice: 'Cesta byla vytvořena.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to trips_path, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:date, :destination, :distance, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consumptions_helper.rb
module ConsumptionsHelper
end

app/helpers/fuels_helper.rb
module FuelsHelper
end

app/helpers/pays_helper.rb
module PaysHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/consumptions/_form.html.erb
<%= form_with(model: consumption, local: true) do |form| %>
  <% if consumption.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(consumption.errors.count, "error") %> prohibited this consumption from being saved:</h2>

      <ul>
      <% consumption.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="row">
      <div class="col s12 m6 offset-m3">
        <div class="card white lighten-3">
          <div class="card-content black-text">
            <span class="card-title black-text">Úprava spotřeby</span>

            <div class="field">
              <%= form.label :value %>
              <%= form.text_field :value, id: :consumption_value %>
            </div>

            <a class="waves-effect waves-light btn">
              <%= form.submit 'upravit' %>
            </a>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/consumptions/edit.html.erb
<%= render 'form', consumption: @consumption %>

app/views/consumptions/index.html.erb
<p id="notice" class="note"><%= notice %></p>

<div class="row">
  <div class="col s12 m6 l6 offset-m3 offset-l3">
    <p  class="title">Spotřeba</p>

    <div class="card white lighten-4">
      <div class="card-content">
        <table class="striped" class="col s12 m6 l10 offset-l1 offset-m3">
          <tbody>
          <% @consumptions.each do |consumption| %>
              <tr>
                <td style="font-weight: 600">Spotřeba</td>
                <td><%= consumption.value %> litrů</td>
                <td>
                  <%= link_to edit_consumption_path(consumption), class: 'btn-floating btn-large waves-effect waves-light green edit' do %>
                      <i class="material-icons" style="line-height: 40px;">edit</i>
                  <% end %>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12 m6 l6 offset-m3 offset-l3">
    <p  class="title">Cena benzínu</p>

    <div class="card white lighten-4">
      <div class="card-content">
        <table class="striped" class="col s12 m6 l10 offset-l1 offset-m3">
          <tbody>
          <% @fuel.each do |fuel| %>
              <tr>
                <td style="font-weight: 600">Cena</td>
                <td><%= fuel.price %> Kč</td>
                <td>
                  <%= link_to edit_fuel_url(fuel), class: 'btn-floating btn-large waves-effect waves-light green edit' do %>
                      <i class="material-icons" style="line-height: 40px;">edit</i>
                  <% end %>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/consumptions/new.html.erb
<%= render 'form', consumption: @consumption %>

<%= link_to 'Back', consumptions_path %>

app/views/consumptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @consumption.value %>
</p>

<%= link_to 'Edit', edit_consumption_path(@consumption) %> |
<%= link_to 'Back', consumptions_path %>

app/views/fuels/_form.html.erb
<%= form_with(model: fuel, local: true) do |form| %>
  <% if fuel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fuel.errors.count, "error") %> prohibited this fuel from being saved:</h2>

      <ul>
      <% fuel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="row">
      <div class="col s12 m6 offset-m3">
        <div class="card white lighten-3">
          <div class="card-content black-text">
            <span class="card-title black-text">Úprava spotřeby</span>

            <div class="field">
              <%= form.label :price %>
              <%= form.text_field :price, id: :fuel_price %>
            </div>

            <a class="waves-effect waves-light btn">
              <%= form.submit 'upravit' %>
            </a>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/fuels/edit.html.erb
<%= render 'form', fuel: @fuel %>

app/views/fuels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fuels</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fuels.each do |fuel| %>
      <tr>
        <td><%= fuel.price %></td>
        <td><%= link_to 'Show', fuel %></td>
        <td><%= link_to 'Edit', edit_fuel_path(fuel) %></td>
        <td><%= link_to 'Destroy', fuel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fuel', new_fuel_path %>

app/views/fuels/new.html.erb
<h1>New Fuel</h1>

<%= render 'form', fuel: @fuel %>

<%= link_to 'Back', fuels_path %>

app/views/fuels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @fuel.price %>
</p>

<%= link_to 'Edit', edit_fuel_path(@fuel) %> |
<%= link_to 'Back', fuels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Benzin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body style="background-color: #f0f0f0;">
  <nav>
    <div class="nav-wrapper blue">
      <a href="#" class="brand-logo center">Jízdy</a>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
        <li><%= link_to  'Přehled', trips_path %></li>
        <li><%= link_to  'Nastavení', consumptions_path %></li>
      </ul>
    </div>
  </nav>


  <%= yield %>
  </body>
</html>

app/views/pays/_form.html.erb
<%= form_with(model: pay, local: true) do |form| %>
  <% if pay.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pay.errors.count, "error") %> prohibited this pay from being saved:</h2>

      <ul>
      <% pay.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="row">
      <div class="col s12 m6 offset-m3">
        <div class="card white lighten-3">
          <div class="card-content white-text">
            <span class="card-title black-text">Vytvoření platby</span>

            <div class="field">
              <%= form.label :price %>
              <%= form.number_field :price, id: :pay_price, class: 'black-text' %>
            </div>

            <a class="waves-effect waves-light btn">
              <%= form.submit 'Zaplatit' %>
            </a>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/pays/edit.html.erb
<%= render 'form', pay: @pay %>

app/views/pays/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pays</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pays.each do |pay| %>
      <tr>
        <td><%= pay.price %></td>
        <td><%= link_to 'Show', pay %></td>
        <td><%= link_to 'Edit', edit_pay_path(pay) %></td>
        <td><%= link_to 'Destroy', pay, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pay', new_pay_path %>

app/views/pays/new.html.erb
<%= render 'form', pay: @pay %>

app/views/pays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @pay.price %>
</p>

<%= link_to 'Edit', edit_pay_path(@pay) %> |
<%= link_to 'Back', pays_path %>

app/views/trips/_form.html.erb
<%= form_with(model: trip, local: true) do |form| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="row">
      <div class="col s12 m6 offset-m3">
        <div class="card white lighten-3">
          <div class="card-content white-text">
            <span class="card-title black-text">Vytvoření cesty</span>
            <div class="field">
              <%= form.label :date %>
              <%= form.text_field :date, id: :trip_date, class: "black-text" %>
            </div>

            <div class="field">
              <%= form.label :destination %>
              <%= form.text_field :destination, id: :trip_destination, class: "black-text"  %>
            </div>

            <div class="field">
              <%= form.label :distance %>
              <%= form.number_field :distance, id: :trip_distance, class: "black-text"  %>
            </div>

            <a class="waves-effect waves-light btn">
              <%= form.submit 'vytvořit' %>
            </a>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/trips/edit.html.erb
<%= render 'form', trip: @trip %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<div class="row">
  <div class="col s12 m10 l10 offset-m1 offset-l1">
    <p  class="title">Přehled jízd</p>

    <div class="card white lighten-4">
      <div class="card-content">

        <%= link_to new_trip_path, class: 'btn-floating halfway-fab waves-effect waves-light red add' do %>
            <i class="material-icons">add</i>
        <% end %>

        <table class="striped" class="col s12 m6 l10 offset-l1 offset-m3">
          <thead>
          <tr>
            <th>Datum</th>
            <th>Kam</th>
            <th>Km</th>
            <th>Cena</th>
            <th></th>
          </tr>
          </thead>

          <tbody>
          <% @trips.each do |trip| %>
              <tr>
                <td><%= trip.date %></td>
                <td><%= trip.destination %></td>
                <td><%= trip.distance %> Km</td>
                <td><%= (@km * trip.distance).round(2) %> Kč</td>
                <td>
                <%= link_to edit_trip_url(trip), class: 'btn-floating btn-large waves-effect waves-light green edit' do %>
                    <i class="material-icons" style="line-height: 40px;">edit</i>
                <% end %>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
        </div>
      </div>
    </div>
</div>

<div class="row col s12 m7 l10 offset-l1">
  <div class="col s12 m8 l5 offset-l1 offset-m2">
    <p  class="title" style="margin-top: 0">Souhrn za měsíc</p>
    <div class="card horizontal">
      <div class="card-stacked">
        <div class="card-content">
          <div class="col s4 m4 l4"><span class="flow-text" style="font-size: 1.4em; font-weight: 600;">Celkem</span></div>
          <div class="col s4 m4 l4"><span class="flow-text" style="font-size: 1.4em;"><%= @distance %> Km</span></div>
          <div class="col s4 m4 l4"><span class="flow-text" style="font-size: 1.4em;"><%= (@km * @distance).round(2) %> Kč</span></div>
        </div>
        <div class="card-action">
          <a href="#">Uzavřít za měsíc <em style="color: #4CAF50;"><%= @date.strftime('%B')%></em></a>
        </div>
      </div>
    </div>
  </div>

  <div class="col s12 m8 l4 offset-l1 offset-m2">
    <p  class="title" style="margin-top: 0">Cena celkem</p>
    <div class="card horizontal">
      <div class="card-stacked">
        <div class="card-content">
          <div class="col s6 l6"><span class="flow-text" style="font-size: 1.4em; font-weight: 600;">K zaplacení</span></div>
          <div class="col s6 l6"><span class="flow-text" style="font-size: 1.4em; font-weight: 600; color:red;"><%= ((@km * @distance) - Pay.sum(:price)).round(2) %> Kč</span></div>

          <div class="col s6 l6"><span class="flow-text" style="font-size: 1.4em; font-weight: 600;">Zaplaceno</span></div>
          <div class="col s6 l6"><span class="flow-text" style="font-size: 1.4em; font-weight: 600; color: #4CAF50;"><%= Pay.sum(:price) %> Kč</span></div>
        </div>
        <div class="card-action">
          <%= link_to 'Zaplatit', new_pay_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/trips/new.html.erb
<%= render 'form', trip: @trip %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @trip.date %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @trip.destination %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @trip.distance %>
</p>

<p>
  <strong>Price:</strong>
  <%= @trip.price %>
</p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>